# Generated by Django 2.2.2 on 2019-06-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
