# Generated by Django 2.2.2 on 2019-07-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
