# Generated by Django 2.2.2 on 2019-10-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
    ]
