# Generated by Django 2.2.2 on 2019-07-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190613_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
