# Generated by Django 2.2.2 on 2019-10-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20191003_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='course.Course'),
        ),
    ]
